### ISSUE TITLE
mysql not working, am I mistaken?

### ISSUE THREAD

**Issue by ManicQuinn** [Skitbet/ActriumGraves#2]
**Describe the bug**
I set "sql" as the storage type and got an error.

**To Reproduce**
Set "sql" as the storage type, fill in the fields and start the server.

Error:
`[02:19:54] [Server thread/INFO]: [ActriumGraves] Enabling ActriumGraves v1.2.1
[02:19:54] [Server thread/INFO]: [ActriumGraves] sql is not a valid storage type!
[02:19:54] [Server thread/INFO]: [ActriumGraves] Disabling ActriumGraves v1.2.1
[02:19:54] [Server thread/ERROR]: Error occurred while disabling ActriumGraves v1.2.1
java.lang.NullPointerException: Cannot invoke "xyz.actrium.graves.managers.StorageManager.getGraveStorage()" because "this.storageManager" is null
	at xyz.actrium.graves.ActriumGraves.onDisable(ActriumGraves.java:76) ~[ActriumGraves-1.2.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:290) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:223) ~[paper-1.20.4.jar:git-Paper-487]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.4.jar:git-Paper-487]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at xyz.actrium.graves.ActriumGraves.disable(ActriumGraves.java:136) ~[ActriumGraves-1.2.1.jar:?]
	at xyz.actrium.graves.config.impl.StorageConfig.loadFields(StorageConfig.java:26) ~[ActriumGraves-1.2.1.jar:?]
	at xyz.actrium.graves.config.ConfigHandler.loadFields(ConfigHandler.java:66) ~[ActriumGraves-1.2.1.jar:?]
	at xyz.actrium.graves.config.ConfigHandler.load(ConfigHandler.java:54) ~[ActriumGraves-1.2.1.jar:?]
	at xyz.actrium.graves.ActriumGraves.onEnable(ActriumGraves.java:59) ~[ActriumGraves-1.2.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-487]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-487]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-487]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-487]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-487]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-487]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-487]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-487]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-487]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
[02:19:54] [Server thread/WARN]: java.lang.IllegalStateException: zip file closed
[02:19:54] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:840)
[02:19:54] [Server thread/WARN]: 	at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:339)
[02:19:54] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.getEntry(JarFile.java:517)
[02:19:54] [Server thread/WARN]: 	at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:472)
[02:19:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209)
[02:19:54] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
[02:19:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169)
[02:19:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164)
[02:19:54] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
[02:19:54] [Server thread/WARN]: 	at ActriumGraves-1.2.1.jar//xyz.actrium.graves.config.impl.GraveConfig.loadFields(GraveConfig.java:30)
[02:19:54] [Server thread/WARN]: 	at ActriumGraves-1.2.1.jar//xyz.actrium.graves.config.ConfigHandler.loadFields(ConfigHandler.java:68)
[02:19:54] [Server thread/WARN]: 	at ActriumGraves-1.2.1.jar//xyz.actrium.graves.config.ConfigHandler.load(ConfigHandler.java:54)
[02:19:54] [Server thread/WARN]: 	at ActriumGraves-1.2.1.jar//xyz.actrium.graves.ActriumGraves.onEnable(ActriumGraves.java:59)
[02:19:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287)
[02:19:54] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188)
[02:19:54] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[02:19:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[02:19:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639)
[02:19:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550)
[02:19:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671)
[02:19:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431)
[02:19:54] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[02:19:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1131)
[02:19:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[02:19:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
[02:19:54] [Server thread/INFO]: [ActriumGraves] Failed to load configuration, please check the config.
[02:19:54] [Server thread/ERROR]: Error occurred while enabling ActriumGraves v1.2.1 (Is it up to date?)
java.lang.IllegalStateException: zip file closed
	at java.util.zip.ZipFile.ensureOpen(ZipFile.java:840) ~[?:?]
	at java.util.zip.ZipFile.getEntry(ZipFile.java:339) ~[?:?]
	at java.util.jar.JarFile.getEntry(JarFile.java:517) ~[?:?]
	at java.util.jar.JarFile.getJarEntry(JarFile.java:472) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:209) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at xyz.actrium.graves.ActriumGraves.registerManagers(ActriumGraves.java:80) ~[ActriumGraves-1.2.1.jar:?]
	at xyz.actrium.graves.ActriumGraves.onEnable(ActriumGraves.java:60) ~[ActriumGraves-1.2.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-487]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-487]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-487]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-487]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-487]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-487]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-487]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-487]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-487]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]`

**Minecraft Version:**
Paper 1.20.4

**Comment by ManicQuinn** [comment]
Just tried something, changed the storage type to "mysql" instead of "sql" like the config suggests, seems to have fixed the issue, dev should change this to reflect the proper wording.

**Comment by Skitbet** [comment]
Ah didnt notice this, will be fixed in next update.
